apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ghcr.io/fmach24/test-api:f5c8d1d5c408a462e83e6287fbda8c44707756c7
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "1.0.0" #TODO version to short sha z github