apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ghcr.io/fmach24/test-api:6637541ebc5198939d52b570fd260aa75fa4a0c6
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "1.0.0" #TODO version to short sha z github